Dota2Blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='list_posts'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete'),
    path('new_post/', views.PostCreateView.as_view(), name='create'),
    path('comment/<int:post_id>/', views.CommentCreateView.as_view(), name='comment'),
    path('heroes', views.HeroListView.as_view(), name='list_heroes'),
    path('posts/<int:pk>/', views.PostHeroFilter.as_view(), name='filtered_post')
]

blog/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

## O modelo Hero é minha classe de categoria, utilizei esse nome 
## para facilitar na hora de criar o programa
class Hero(models.Model):
    name = models.CharField(max_length=20)
    relative_url = models.CharField(max_length=220)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    LANE_CHOICES = [
        ('B', 'Bottom Lane'),
        ('T', 'Top Lane'),
        ('M', 'Mid Lane'),
    ]
    lane = models.CharField(
        max_length=1,
        choices=LANE_CHOICES
        )
    
    POSITION_CHOICES=[
        ('1', 'Midlaner'),
        ('2', 'Hard Carrier'),
        ('3', 'Offlaner'),
        ('4', 'Suport 4'),
        ('5', 'Suport 5')
    ]
    position = models.CharField(
        max_length=1,
        choices=POSITION_CHOICES,
    )

    dota_version = models.CharField(max_length=7, default='7.31c')

    heroes = models.ManyToManyField(Hero, related_name='posts', through = "Hero_Post")

    def __str__(self):
        return self.title

class Hero_Post(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='hero_post')
    hero = models.ForeignKey(Hero, on_delete=models.CASCADE, related_name='hero_post')


    CATEGORY_CHOICES = [
        ('1', 'Main Hero'),
        ('2', 'Teammate Hero'),
        ('3', 'Enemy Hero'),
    ]
    hero_category = models.CharField(
        max_length=1,
        choices=CATEGORY_CHOICES,
    )

    def __str__(self):
        return self.post.title + ' - ' + self.hero.name + ' - ' + self.hero_category

class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "comentário de " + self.user.username + " no post " + self.post.title

blog/views.py
import markdown
from markdownify import markdownify
from django.views import generic
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse
from .models import Post, Hero, Hero_Post, Comment
from django.contrib.auth import get_user_model
from .form import PostForm

# Create your views here.
class PostListView(generic.ListView):
    model = Post
    template_name = 'blog/home.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'
    
class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostForm
    success_url = '/{id}/'
    template_name = 'blog/create.html'
 
    def form_valid(self, form):
        new_post = form.save(commit=False)
        new_post.content = markdown.markdown(form.cleaned_data['content'])
        new_post.save()
        form.save_m2m()

        main_hero = form.cleaned_data['main_hero']
        enemy1 = form.cleaned_data['enemy1']
        teammate = form.cleaned_data['teammate_hero']
        enemy2 = form.cleaned_data['enemy2']

        new_post.heroes.add(main_hero, through_defaults={'hero_category': '1'})
        new_post.heroes.add(enemy1, through_defaults={'hero_category': '3'})
        if enemy2:
            new_post.heroes.add(enemy2, through_defaults={'hero_category': '3'})
            new_post.heroes.add(teammate, through_defaults={'hero_category': '2'})

        return HttpResponseRedirect(
            reverse('blog:detail', args=(new_post.id, )))

class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = PostForm
    success_url = '/{id}/'
    template_name = 'blog/update.html'

    def get_initial(self):
        initial = super().get_initial()
        initial['main_hero'] = super().get_object().hero_post.get(hero_category=1).hero
        initial['enemy1'] = super().get_object().hero_post.filter(hero_category=3)[0].hero
        initial['content'] = markdownify(super().get_object().content)
        if super().get_object().hero_post.filter(hero_category=2).exists():
            initial['teammate_hero'] = super().get_object().hero_post.get(hero_category=2).hero
            initial['enemy2'] = super().get_object().hero_post.filter(hero_category=3)[1].hero
        return initial

    def form_valid(self, form):
        new_post = form.save(commit=False)
        new_post.content = markdown.markdown(form.cleaned_data['content'])
        new_post.save()
        form.save_m2m()

        main_hero = form.cleaned_data['main_hero']
        enemy1 = form.cleaned_data['enemy1']
        teammate = form.cleaned_data['teammate_hero']
        enemy2 = form.cleaned_data['enemy2']

        new_post.heroes.add(main_hero, through_defaults={'hero_category': '1'})
        new_post.heroes.add(enemy1, through_defaults={'hero_category': '3'})
        if enemy2:
            new_post.heroes.add(enemy2, through_defaults={'hero_category': '3'})
            new_post.heroes.add(teammate, through_defaults={'hero_category': '2'})

        return HttpResponseRedirect(
            reverse('blog:detail', args=(new_post.id, )))

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'blog/delete.html'
    context_object_name = 'post'
    success_url = '/'

class CommentCreateView(generic.CreateView):
    model = Comment
    fields = ['content']
    template_name = 'blog/create_comment.html'

    def dispatch(self, request, post_id):
        self.initial = {
            'post': Post.objects.get(pk=post_id),
            'user': get_user_model().objects.all()[1]
        }
        return super().dispatch(request, post_id)

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        new_comment.post = self.initial['post']
        new_comment.user = self.initial['user']
        new_comment.save()
        form.save_m2m()

        return HttpResponseRedirect(
            reverse('blog:detail', args=(new_comment.post.id, )))

class HeroListView(generic.ListView):
    model = Hero
    template_name = 'blog/list_heroes.html'
    context_object_name = 'heroes'

class PostHeroFilter(generic.DetailView):
    model = Hero
    template_name = 'blog/list_filtered_posts.html'
    context_object_name = 'hero'

blog/templates/blog/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block css_imports%}
    <link rel="stylesheet" type="text/css" href="{% static 'style/list_posts.css' %}">
{% endblock css_imports %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
<div id="home-posts-list">

        {% for post in object_list %}
            <div class="post-holder">
                <a class="post-viewer" href="{% url 'blog:detail' post.id %}">
                    <div class="post-title"><h1>{{post.title}}</h1></div>
                    <div class="post-heroes">
                        {% for hero_post in post.hero_post.all|dictsort:"hero_category" %}
                            {% if hero_post.hero_category == "1" %}
                                <div class="hero teammates main-hero">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% elif hero_post.hero_category == "2" %}
                                <div class="hero teammates">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% endif %}
                        {% endfor %}

                        <div class="versus">
                            <img src="{% static 'versus_icon.png' %}">
                        </div>

                        {% for hero_post in post.hero_post.all|dictsort:"hero_category" %}
                            {% if hero_post.hero_category == "3" %}
                                <div class="hero enemies">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <p class="post-date"> {{post.date|date}} </p>
                </a>
                <a href="{% url 'blog:delete' post.id %}" class="button delete-post"> Delete </a>
                <a href="{% url 'blog:update' post.id %}" class="button update-post"> Update </a>
            </div>
        {% endfor %}
</div>
{% endblock content %}

blog/templates/blog/create.html
{% extends 'base.html' %}
{% load static %}

{% block css_imports%}
    <link rel="stylesheet" type="text/css" href="{% static 'style/detail_post.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style/list_posts.css' %}">
{% endblock css_imports %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
<div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar Post</button>
    </form>
</div>
{% endblock content %}

blog/templates/blog/create_comment.html
{% extends 'base.html' %}
{% load static %}

{% block css_imports%}
    <link rel="stylesheet" type="text/css" href="{% static 'style/detail_post.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style/list_posts.css' %}">
{% endblock css_imports %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
<div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar Post</button>
    </form>
</div>
{% endblock content %}

blog/templates/blog/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
    <div style="text-align: center;">
        <h1> Tem certeza que deseja deletar o post com título {{ post.title }} ?</h1>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn-default btn" name="submit" access="false" style="default" id="submit">DELETAR</button>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}

{% block css_imports%}
    <link rel="stylesheet" type="text/css" href="{% static 'style/detail_post.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style/list_posts.css' %}">
{% endblock css_imports %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
    <div id="post-block">
        <div class="post-heroes">
            {% for hero_post in post.hero_post.all|dictsort:"hero_category" %}
            {% if hero_post.hero_category == "1" %}
            <div class="hero teammates main-hero">
                <p> {{ hero_post.hero.name }} </p>
                <a href="{% url 'blog:filtered_post' hero_post.hero.id %}">
                    <img src="{% static hero_post.hero.relative_url %}">
                </a>
            </div>
            {% elif hero_post.hero_category == "2" %}
            <div class="hero teammates">
                        <p> {{ hero_post.hero.name }} </p>
                        <a href="{% url 'blog:filtered_post' hero_post.hero.id %}">
                            <img src="{% static hero_post.hero.relative_url %}">
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                    
                    <div class="versus">
                        <img src="{% static 'versus_icon.png' %}">
            </div>

            {% for hero_post in post.hero_post.all|dictsort:"hero_category" %}
            {% if hero_post.hero_category == "3" %}
            <div class="hero enemies">
                <p> {{ hero_post.hero.name }} </p>
                <a href="{% url 'blog:filtered_post' hero_post.hero.id %}">
                    <img src="{% static hero_post.hero.relative_url %}">
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        
        <div class="post-content-block">
            <h1> {{post.title}}</h1>
            {{ post.content|safe }}
        </div>
    </div>

    <div id="comment-block">
        <a href="{% url 'blog:comment' post.id %}" id="add-comment-link"> Criar um comentário </a>
        {% for comment in post.comments.all|dictsortreversed:"date" %}
            <div class="comment">
                <p> Usuário {{ comment.user.username }} comentou</p>
                <p> {{ comment.content }} </p>
                <p class="comment-date"> {{ comment.date }} </p>
            </div>
        {% endfor %}
    </div>
    {% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% load static %}

{% block css_imports%}
    <link rel="stylesheet" type="text/css" href="{% static 'style/list_posts.css' %}">
{% endblock css_imports %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
<div id="home-posts-list"> 

        {% for post in object_list %}
            <div class="post-holder">
                <a class="post-viewer" href="{% url 'blog:detail' post.id %}">
                    <div class="post-title"><h1>{{post.title}}</h1></div>
                    <div class="post-heroes">
                        {% for hero_post in post.hero_post.all|dictsort:"hero_category" %}
                            {% if hero_post.hero_category == "1" %}
                                <div class="hero teammates main-hero">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% elif hero_post.hero_category == "2" %}
                                <div class="hero teammates">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% endif %}
                        {% endfor %}

                        <div class="versus">
                            <img src="{% static 'versus_icon.png' %}">
                        </div>

                        {% for hero_post in post.hero_post.all|dictsort:"hero_category" %}
                            {% if hero_post.hero_category == "3" %}
                                <div class="hero enemies">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <p class="post-date"> {{post.date|date}} </p>
                </a>
                <a href="{% url 'blog:delete' post.id %}" class="button delete-post"> Delete </a>
                <a href="{% url 'blog:update' post.id %}" class="button update-post"> Update </a>
            </div>
        {% endfor %}
</div>
{% endblock content %}

blog/templates/blog/list_filtered_posts.html
{% extends 'base.html' %}
{% load static %}

{% block css_imports%}
    <link rel="stylesheet" type="text/css" href="{% static 'style/list_posts.css' %}">
{% endblock css_imports %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
<div id="home-posts-list"> 

        {% for post in hero.posts.all %}
            <div class="post-holder">
                <a class="post-viewer" href="{% url 'blog:detail' post.id %}">
                    <div class="post-title"><h1>{{post.title}}</h1></div>
                    <div class="post-heroes">
                        {% for hero_post in post.hero_post.all|dictsort:"hero_category" %}
                            {% if hero_post.hero_category == "1" %}
                                <div class="hero teammates main-hero">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% elif hero_post.hero_category == "2" %}
                                <div class="hero teammates">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% endif %}
                        {% endfor %}

                        <div class="versus">
                            <img src="{% static 'versus_icon.png' %}">
                        </div>

                        {% for hero_post in post.hero_post.all|dictsort:"hero_category" %}
                            {% if hero_post.hero_category == "3" %}
                                <div class="hero enemies">
                                    <p> {{ hero_post.hero.name }} </p>
                                    <img src="{% static hero_post.hero.relative_url %}">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <p class="post-date"> {{post.date|date}} </p>
                </a>
                <a href="{% url 'blog:delete' post.id %}" class="button delete-post"> Delete </a>
                <a href="{% url 'blog:update' post.id %}" class="button update-post"> Update </a>
            </div>
        {% endfor %}
</div>
{% endblock content %}

blog/templates/blog/list_heroes.html
{% extends 'base.html' %}
{% load static %}

{% block css_imports%}
    <link rel="stylesheet" type="text/css" href="{% static 'style/main_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style/heroes_list.css' %}">
{% endblock css_imports %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
<div id="heroes-list" class="heroes-list">
    {% for hero in heroes %}
        <div class="hero">
            <p class="hero-name"> {{hero.name}} </p>
            <a href="{% url 'blog:filtered_post' hero.id %}">
                <img class="hero-icon" src="{% static hero.relative_url %}">
            </a>
        </div>
    {% endfor %}
</div>
{% endblock content %}

blog/templates/blog/update.html
{% extends 'base.html' %}
{% load static %}

{% block css_imports%}
    <link rel="stylesheet" type="text/css" href="{% static 'style/detail_post.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style/list_posts.css' %}">
{% endblock css_imports %}

{% block title %}
Dota 2 Blog
{% endblock title %}

{% block content %}
<div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Atualizar Post</button>
    </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'style/main_style.css' %}">
    {% block css_imports %}{% endblock %}
</head>

<body>
    <header>
        <div id="header-image"></div>
        <div id="main-navigation">
            <nav id="navegacao-principal">
                <ul class="horizontal-navigation">
                    <li><a href="{% url 'blog:list_posts' %}"> Blog </a></li>
                    <li><a href="{% url 'blog:create' %}"> Criar Post </a></li>
                    <li><a href="{% url 'blog:list_heroes' %}">Filtrar Heroi</a></li>
                </ul>
            </nav>
        </div>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>